# Site settings
gems:
  - jekyll-redirect-from
title: Manly Vegetarian
email: p.e.butler3@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Manly Vegetarian! Your're home for vegetarian recipes
  that will fill you up and keep the beard growing!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://manlyvegetarian.gq"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
